
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

#support proxy
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.0.0/24
    - 192.168.192.0/24
    - 172.16.0.0/12

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
