
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

#support proxy
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.0.0/24
    - 192.168.192.0/24
    - 172.16.0.0/12

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#WOL Button
switch:
  - platform: wake_on_lan
    name: "XuauGame"                 # 定义HA中实体的名称,可任意命名
    mac: "D8-43-AE-9D-74-D5"        # 主机(电脑)的MAC地址
    host: "192.168.2.2"            # 主机(电脑)地址,可省略
    broadcast_address: "192.168.2.1"      # 广播地址.不可省略.此处假设路由器地址为192.168.1.1,如为其他网段需要修改
