homeassistant:
  packages: !include_dir_named packages/

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
  dashboards:
    mattias-lovelace:
      mode: yaml
      title: Mattias
      icon: mdi:tablet-cellphone
      show_in_sidebar: true
      filename: dashboards/tablet/ui-lovelace.yaml

# Text-to-speech
tts:
  - platform: google_translate

#support proxy
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.0.0/24
    - 192.168.192.0/24
    - 172.16.0.0/12

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include custom_sensors.yaml

#WOL Button
switch:
  - platform: wake_on_lan
    name: "XuauGame"                 # 定义HA中实体的名称,可任意命名
    mac: "D8:43:AE:9D:74:D5"        # 主机(电脑)的MAC地址
    host: "192.168.2.2"            # 主机(电脑)地址,可省略
    broadcast_address: "192.168.2.255"      # 广播地址.不可省略.此处假设路由器地址为192.168.1.1,如为其他网段需要修改
    broadcast_port: 9
    turn_off: 
      service: shell_command.turn_off_connect

script:
  open_steam:
    alias: Open Steam Bigpicture
    sequence:
      - service: shell_command.turn_on_steam

shell_command:
  turn_off_connect: 'ssh -i /config/.ssh/id_rsa xuche@192.168.2.2 "shutdown /s /t 10"'
  turn_on_steam: 'ssh -i /config/.ssh/id_rsa xuche@192.168.2.2 "schtasks /run /tn \"MyFlow\\RunSteam\""'

# Example configuration.yaml entry
input_boolean:
  gamemode:
    name: "游戏模式"
    icon: mdi:nintendo-switch

input_select:
  badroom_mode:
    name: "卧室场景模式"
    options:
      - "起床"
      - "入睡"
      - "观影"
      - "白天"
    initial: "起床"
    icon: "mdi:home-automation"
