urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:1: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:6
urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:2: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:6
urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:3: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:6
urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:4: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:6
urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:5: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:6
urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-m9:6:
  prop.10.6:
    unit: none
urn:miot-spec-v2:device:air-monitor:0000A008:cgllc-s1:1:
  prop.2.5:
    name: voc-density
urn:miot-spec-v2:device:airer:0000A00D:hyd-lyjpro:1:
  prop.2.3:
    name: current-position-a
  prop.2.8:
    name: target-position-a
  prop.2.9:
    name: target-position-b
urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj5:1:
  prop.2.3:
    value-range:
    - 0
    - 1
    - 1
urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj5:2: urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj5:1
urn:miot-spec-v2:device:airer:0000A00D:mrbond-m33a:1:
  prop.2.3:
    name: current-position-a
  prop.2.11:
    name: current-position-b
urn:miot-spec-v2:device:bath-heater:0000A028:mike-2:1:
  prop.3.1:
    name: mode-a
  prop.3.11:
    name: mode-b
  prop.3.12:
    name: mode-c
urn:miot-spec-v2:device:bath-heater:0000A028:opple-acmoto:1:
  prop.5.2:
    value-list:
    - value: 1
      description: low
    - value: 128
      description: medium
    - value: 255
      description: high
urn:miot-spec-v2:device:bath-heater:0000A028:xiaomi-s1:1:
  prop.4.4:
    name: fan-level-ventilation
urn:miot-spec-v2:device:fan:0000A005:dmaker-p5:1:
  prop.2.6:
    name: fan-level-a
urn:miot-spec-v2:device:fan:0000A005:xiaomi-p51:1:
  prop.2.2:
    name: fan-level-a
urn:miot-spec-v2:device:fan:0000A005:zhimi-v3:3:
  prop.2.6:
    name: fan-level-a
urn:miot-spec-v2:device:gateway:0000A019:lumi-mcn001:1:
  prop.2.1:
    access:
    - read
    - notify
  prop.2.2:
    icon: mdi:ip
  prop.2.3:
    access:
    - read
    - notify
  prop.2.5:
    access:
    - read
    - notify
urn:miot-spec-v2:device:gateway:0000A019:xiaomi-hub1:1:
  prop.2.1:
    name: access-mode
    access:
    - read
    - notify
  prop.2.2:
    name: ip-address
    icon: mdi:ip
  prop.2.3:
    name: wifi-ssid
    access:
    - read
    - notify
urn:miot-spec-v2:device:gateway:0000A019:xiaomi-hub1:2: urn:miot-spec-v2:device:gateway:0000A019:xiaomi-hub1:1
urn:miot-spec-v2:device:gateway:0000A019:xiaomi-hub1:3: urn:miot-spec-v2:device:gateway:0000A019:xiaomi-hub1:1
urn:miot-spec-v2:device:kettle:0000A009:yunmi-r3:1:
  prop.3.1:
    unit: ppm
urn:miot-spec-v2:device:light:0000A001:shhf-sfla12:1:
  prop.8.11:
    name: on-a
urn:miot-spec-v2:device:magnet-sensor:0000A016:linp-m1:1:
  prop.2.1004:
    name: contact-state
    expr: src_value!=1
urn:miot-spec-v2:device:motion-sensor:0000A014:lumi-acn001:1:
  prop.3.2:
    access:
    - read
    - notify
    unit: mV
urn:miot-spec-v2:device:occupancy-sensor:0000A0BF:izq-24:2:0000C824:
  prop.2.6:
    unit: cm
urn:miot-spec-v2:device:occupancy-sensor:0000A0BF:linp-hb01:2:0000C824:
  prop.3.3:
    unit: m
urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:1: urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:3
urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:2: urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:3
urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:3:
  prop.5.1:
    expr: round(src_value*6/1000000, 3)
urn:miot-spec-v2:device:outlet:0000A002:cuco-cp1md:1:
  prop.2.2:
    name: power-consumption
    expr: round(src_value/1000, 3)
  prop.2.3:
    expr: round(src_value/10, 1)
  prop.2.4:
    unit: mA
urn:miot-spec-v2:device:outlet:0000A002:cuco-cp2:1: urn:miot-spec-v2:device:outlet:0000A002:cuco-cp2:2
urn:miot-spec-v2:device:outlet:0000A002:cuco-cp2:2:
  prop.2.3:
    expr: round(src_value/10, 1)
  prop.2.4:
    unit: mA
  prop.3.2:
    expr: round(src_value/10, 1)
urn:miot-spec-v2:device:outlet:0000A002:cuco-v3:1:
  prop.11.1:
    name: power-consumption
    expr: round(src_value/100, 2)
urn:miot-spec-v2:device:outlet:0000A002:cuco-v3:2: urn:miot-spec-v2:device:outlet:0000A002:cuco-v3:1
urn:miot-spec-v2:device:outlet:0000A002:giot-v8icm:1:0000C816:
  prop.4.1:
    unit: mWh
urn:miot-spec-v2:device:outlet:0000A002:qmi-psv3:1:0000C816:
  prop.3.3:
    unit: mV
  prop.3.4:
    unit: mA
urn:miot-spec-v2:device:outlet:0000A002:zimi-zncz01:1:0000C816: urn:miot-spec-v2:device:outlet:0000A002:zimi-zncz01:2:0000C816
urn:miot-spec-v2:device:outlet:0000A002:zimi-zncz01:2:0000C816:
  prop.3.1:
    name: electric-power
    expr: round(src_value/100, 2)
urn:miot-spec-v2:device:plant-monitor:0000A030:hhcc-v1:1:
  prop.2.1:
    name: soil-moisture
    icon: mdi:watering-can
  prop.2.2:
    name: soil-ec
    icon: mdi:sprout-outline
    unit: Î¼S/cm
urn:miot-spec-v2:device:relay:0000A03D:lumi-c2acn01:1:
  prop.4.1:
    unit: kWh
urn:miot-spec-v2:device:router:0000A036:xiaomi-rd08:1:
  prop.2.1:
    name: download-speed
    icon: mdi:download
    unit: B/s
  prop.2.2:
    name: upload-speed
    icon: mdi:upload
    unit: B/s
urn:miot-spec-v2:device:safe-box:0000A042:loock-v1:1:
  prop.5.1:
    name: contact-state
    expr: src_value!=1
urn:miot-spec-v2:device:thermostat:0000A031:suittc-wk168:1:
  prop.2.3:
    value-list:
    - value: 1
      description: '1'
    - value: 2
      description: '2'
    - value: 3
      description: '3'
    - value: 4
      description: '4'
    - value: 5
      description: '5'
    - value: 6
      description: '6'
    - value: 7
      description: '7'
    - value: 8
      description: '8'
    - value: 9
      description: '9'
    - value: 10
      description: '10'
    - value: 11
      description: '11'
    - value: 12
      description: '12'
    - value: 13
      description: '13'
    - value: 14
      description: '14'
    - value: 15
      description: '15'
    - value: 16
      description: '16'
urn:miot-spec-v2:device:water-purifier:0000A013:roswan-lte01:1:0000D05A:
  prop.4.1:
    unit: ppm
  prop.4.2:
    unit: ppm
urn:miot-spec-v2:device:water-purifier:0000A013:yunmi-s20:1:
  prop.4.1:
    unit: ppm
  prop.4.2:
    unit: ppm
