---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks
- PT:
  - MTeam:
    - abbr: MT
      href: https://zp.m-team.io/index
      description: 馒头
  - Kufei:
    - abbr: PT
      href: https://kufei.org/torrents.php
      description: 库非
  - Cafei:
    - abbr: PT
      href: https://ptcafe.club/torrents.php
      description: 咖啡

- Management:
  - mojievpn:
    - abbr: MJ
      href: https://mojie.me/#/dashboard
      description: VPN
  - Excahange:
    - abbr: EX
      href: https://exchange.xuchengcat.cn
      description: 交换机
  - ZeroTier:
    - icon: /icons/zerotier.png
      href: https://my.zerotier.com/network/abfd31bd470eb354/
      description: 内网穿透
  - Render:
    - abbr: BA
      href: https://dashboard.render.com/
      description: bark server

- Luntan:
  - Hassbian:
    - abbr: HA
      href: https://bbs.hassbian.com/
      description: 智能家居
  - Enshan:
    - abbr: ES
      href: https://www.right.com.cn/forum/
      description: 软路由
  - Reddit:
    - icon: /icons/reddit.png
      href: https://reddit.com/
      description: " "

- Outside:
    - Github:
        - icon: /icons/github.png
          href: https://github.com/xuchengcat/ServerBkp/
          description: " "
    - YouTube:
        - icon: /icons/youtube.png
          href: https://youtube.com/
          description: " "
