---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

statusStyle: "dot"
useEqualHeights: true

layout:
  System Monitor:
    header: false
    style: row
    columns: 4
  NA Area:
    header: false
    style: row
    columns: 4
  HA Area:
    header: false
    style: row
    columns: 4
  MA Area:
    header: false
    style: row
    columns: 4
  # providers:
  #openweathermap: openweathermapapikey
  #weatherapi: weatherapiapikey
